//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociateRole
    {
        public int AssociateRoleID { get; set; }
        public int AccountID { get; set; }
        public int RoleID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
