//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociateLink
    {
        public int AssociateLinkID { get; set; }
        public int RoleID { get; set; }
        public int LinkID { get; set; }
    
        public virtual Link Link { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
